repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^\.specstory/
      - id: end-of-file-fixer
        exclude: ^\.specstory/
      - id: check-yaml
        exclude: ^\.specstory/
      - id: check-added-large-files
        exclude: ^\.specstory/
      - id: check-merge-conflict
        exclude: ^\.specstory/
      - id: debug-statements
        exclude: ^\.specstory/
      - id: check-case-conflict
        exclude: ^\.specstory/
      - id: check-docstring-first
        exclude: ^\.specstory/
      - id: check-json
        exclude: ^\.specstory/
      - id: check-symlinks
        exclude: ^\.specstory/
      - id: check-toml
        exclude: ^\.specstory/
      - id: detect-private-key
        exclude: ^\.specstory/
      - id: requirements-txt-fixer
        exclude: ^\.specstory/

  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        language_version: python3
        files: ^(map_locations/|map_locations_ai/|tests/)

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]
        files: ^(map_locations/|map_locations_ai/|tests/)

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        files: ^(map_locations/|tests/)
      # Separate lenient flake8 for AI package
      - id: flake8
        alias: flake8-ai
        args: [--extend-ignore=E226]
        files: ^(map_locations_ai/)

  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: python
        args: [--level=error]
        files: ^(map_locations/.*\.py)$
        additional_dependencies: [pyright]
      # Separate lenient pyright for AI package
      - id: pyright-ai
        name: pyright-ai
        entry: pyright
        language: python
        args: [
          --level=warning,
          --skipunannotated
        ]
        files: ^(map_locations_ai/.*\.py)$
        additional_dependencies: [pyright]

  # Optional: Add pytest hook (commented out by default for speed)
  # Uncomment if you want tests to run on every commit
  # - repo: local
  #   hooks:
  #     - id: pytest-fast
  #       name: pytest-fast
  #       entry: pytest
  #       language: python
  #       args: [tests/, -v, --tb=short, -x]  # Stop on first failure
  #       files: ^(tests/|map_locations/)
  #       pass_filenames: false
