# Map Locations AI - Configuration

# LLM Settings
llm:
  model: "gpt-4o-mini"  # Can be changed to "gpt-4o" for production
  temperature: 0.1      # Low temperature for consistent extraction
  max_tokens: 2000      # Sufficient for location extraction responses
  timeout: 120          # Increased timeout in seconds for API calls

# Processing Settings
processing:
  chunk_size: 50        # Reduced chunk size for faster processing
  overlap_size: 10      # Number of overlapping lines between chunks

# Output Settings
output:
  temp_dir: "map_locations_ai/temp"      # Directory for temporary YAML files
  trace_dir: "map_locations_ai/trace"    # Directory for trace logs
  chunk_prefix: "chunk" # Prefix for chunk files (chunk_001.yaml, etc.)

# Deduplication Settings
deduplication:
  similarity_threshold: 0.70    # Minimum similarity score for duplicate detection (0.0-1.0)
  name_weight: 0.4             # Weight for name similarity in scoring
  type_weight: 0.2             # Weight for type matching in scoring
  description_weight: 0.25     # Weight for description similarity in scoring
  source_weight: 0.15          # Weight for source context similarity in scoring
  merge_strategy:
    name: "highest_confidence"  # Strategy: "highest_confidence" or "longest"
    type: "most_specific"       # Strategy: "most_specific" or "highest_confidence"
    description: "longest"      # Strategy: "longest" or "highest_confidence"
    confidence: "weighted_average"  # Strategy: "weighted_average" or "highest"
    source_text: "concatenate"  # Strategy: "concatenate" or "highest_confidence"

# Enrichment Settings
enrichment:
  enabled: true                 # Enable location enrichment
  model: "gpt-4o-mini"         # Model to use for enrichment
  max_searches_per_location: 3  # Maximum search operations per location
  temperature: 0.1             # Temperature for LLM calls
  timeout: 120                 # Timeout for LLM calls in seconds
  priority_fields:             # Fields to prioritize during enrichment
    - "latitude"               # Geographic coordinates (critical)
    - "longitude"              # Geographic coordinates (critical)
    - "name"                   # Official name verification
    - "description"            # Tourist-friendly description
    - "official_website"       # Official website URL
    - "opening_hours"          # Operating hours
  batch_size: 10               # Number of locations to process in batch
  rate_limit_delay: 1.0        # Delay between enrichment calls (seconds)
