# Map Locations AI - Configuration

# LLM Settings
llm:
  # Model configurations for different processing steps
  # You can specify different models for different steps to optimize cost/performance
  models:
    extraction: "gpt-4o"    # Model for initial location extraction (fast, cost-effective)
    enrichment: "gpt-4o"         # Model for location enrichment (more powerful for complex tasks)
    geocoding: "gpt-4o"     # Model for geocoding assistance (if needed)
    deduplication: "gpt-4o" # Model for deduplication analysis (if needed)
  # Default model (used when specific step model not specified)
  model: "gpt-4o"  # Can be changed to "gpt-4o" for production
  temperature: 0.1      # Low temperature for consistent extraction
  max_tokens: 2000      # Sufficient for location extraction responses
  timeout: 120          # Increased timeout in seconds for API calls

# Processing Settings
processing:
  chunk_size: 50        # Reduced chunk size for faster processing
  overlap_size: 10      # Number of overlapping lines between chunks

# Output Settings
output:
  temp_dir: "map_locations_ai/temp"      # Directory for temporary YAML files
  trace_dir: "map_locations_ai/trace"    # Directory for trace logs
  chunk_prefix: "chunk" # Prefix for chunk files (chunk_001.yaml, etc.)

# Deduplication Settings
deduplication:
  similarity_threshold: 0.75    # Increased from 0.70 for more precision
  name_weight: 0.35            # Reduced from 0.4 to balance with new factors
  type_weight: 0.15            # Reduced from 0.2 to balance with new factors
  description_weight: 0.35     # Increased from 0.25 for better content matching
  address_weight: 0.10         # NEW: Weight for address similarity
  source_weight: 0.05          # Reduced from 0.15 to balance with new factors
  merge_strategy:
    name: "highest_confidence"  # Strategy: "highest_confidence" or "longest"
    type: "most_specific"       # Strategy: "most_specific" or "highest_confidence"
    description: "longest"      # Strategy: "longest" or "highest_confidence"
    confidence: "weighted_average"  # Strategy: "weighted_average" or "highest"
    source_text: "concatenate"  # Strategy: "concatenate" or "highest_confidence"

# Enrichment Settings
enrichment:
  enabled: true                 # Enable location enrichment
  model: "gpt-4o-mini"         # Model to use for enrichment
  max_searches_per_location: 3  # Maximum search operations per location
  timeout: 120                 # Timeout for LLM calls in seconds
  max_retries: 2               # Maximum retries for JSON parsing failures
  priority_fields:             # Fields to prioritize during enrichment
    - "latitude"               # Geographic coordinates (critical)
    - "longitude"              # Geographic coordinates (critical)
    - "name"                   # Official name verification
    - "description"            # Tourist-friendly description
    - "official_website"       # Official website URL
    - "opening_hours"          # Operating hours
  batch_size: 10               # Number of locations to process in batch
  rate_limiting:               # Rate limiting configuration for concurrent processing
    max_concurrent_calls: 2    # Maximum concurrent API calls (reduced to avoid rate limits)
    min_request_interval: 1.0  # Minimum seconds between requests (legacy, not used)
    max_requests_per_minute: 30 # Maximum requests per minute (legacy, not used)
    retry_on_rate_limit: true  # Retry with backoff when rate limited
    backoff_multiplier: 2.0    # Multiplier for exponential backoff
